USE present;

CREATE TABLE todos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	text VARCHAR(200),
	state BOOLEAN NOT NULL
);


	-- ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	-- dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

-- INSERT INTO users(email, password)
-- VALUES("a@b.com", "funcking77")

-- DELETE FROM users;

-- SELECT * from users;
DESC todos;
